### ISSUE TITLE
labeling function of the result magic

### ISSUE THREAD

**Issue by BinchaoPeng** [xingzhaolee/pedestrian-attribute-recognition-lightning#1]
in your project， do you have labeling function of the result magic，like  labeling person‘s shoes、bags and so on

**Comment by xingzhaolee** [comment]
sorry what do you mean?

**Comment by BinchaoPeng** [comment]
就是，请问有图片标注的功能吗？

**Comment by xingzhaolee** [comment]
nope. I don't have it.
